version: "3"
services:
  app:
    build: .
    ports:
      - 8085:80
    volumes:
      - .:/var/www/html
    links:
      - mysql

  mysql:
    image: mysql:5.7.28
    ports:
      - 33066:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=hw_7_Tolkachev




